#!/usr/bin/env bash
# Setting up a Load balancer

sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install haproxy

echo "
frontend Local_Server
    bind *:80
    mode http
    default_backend My_Web_Servers

backend My_Web_Servers
    mode http
    balance roundrobin
    server 431-web-01 34.73.192.230:80 check
    server 431-web-02 34.239.179.149:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
