#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but for the 9th iteration, displays Best School and then Hi on a new line.
greeting=1
while [ $greeting -le 10 ]
do
    echo "Best School"
    greeting=$(( greeting + 1 ))
    if [ $greeting -eq 10 ]
    then
        echo "Hi"
    fi
done
