#!/usr/bin/env bash
#  Displays  "Bad luck", "Good luck" and "Best School", for the 4th, 8th and other iterations, respectivery.
i=1
while [ $i -le 10 ]
do 
	if [ $i -eq 4 ]
	then
		echo "bad luck"
    elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i + 1 ))
done