#!/usr/bin/env bash
#  Displays  "bad luck from China", "bad luck from Japan" and "bad luck from Italy", for the 4th, 9th and other iterations, respectivery.
i=1
counter=1
while [ $i -le 20 ]
do 
	echo "$i"
	case $i in
	4)
		echo "bad luck from China"
	;;

    9)
		echo "bad luck from Japan"
	;;
	17)
		echo "bad luck from Italy"
		((counter++))
	esac
	i=$(( i + 1 ))
done
